replicaCount: 2

argocd:
  host: argo-demo.mario.com

app:
  host: demo-app.mario.com

prometheus:
  host: prometheus.mario.com

image:
  repository: roshaneishara/argo-canary-demo-app
  tag: v15
  pullPolicy: Always

service:
  port: 80
  targetPort: 5000

rollout:
  steps:
    - setWeight: 10
    - pause: { duration: 30s }
    - setWeight: 30
    - pause: { duration: 30s }
    - setWeight: 50
    - pause: { duration: 30s }
    - setWeight: 80
    - pause: { duration: 30s }


