replicaCount: 2

argocd:
  host: argo-demo.mario.com

app:
  host: demo-app.mario.com

prometheus:
  host: prometheus.mario.com

image:
  repository: roshaneishara/argo-canary-demo-app
  tag: v27
  pullPolicy: Always

service:
  port: 80
  targetPort: 5000

rollout:
   #Template with Analysis steps with prometheus metrics to automatically promote or rollback based on the success rate of the canary version
  steps:
    - setWeight: 10
    - pause: { duration: 30s }
    - analysis:
        templates:
        - templateName: istio-success-rate
        args:
        - name: service-name
          value: demo-app-canary.demo.svc.cluster.local
        - name: namespace
          value: demo
    - setWeight: 50
    - pause: {duration: 30s}
    - analysis:
        templates:
        - templateName: istio-success-rate
        args:
        - name: service-name
          value: demo-app-canary.demo.svc.cluster.local
        - name: namespace
          value: demo

  # Template with Manual Promote step
  # steps:
  # - setWeight: 10
  # - pause: {}  # Waits for manual promotion
  # - setWeight: 50
  # - pause: {duration: 30s}


