apiVersion: v1
kind: Service #Service so prometheus scrapes metrics from Envoy sidecar
metadata:
  name: demo-app
  namespace: demo
  labels:
    app: demo-app
spec:
  selector:
    app: demo-app
  ports:
    - name: http-envoy-prom
      port: 15090
      targetPort: 15090