apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: prometheus-ui
spec:
  gateways: 
    - demo-app-gateway
  hosts:
    - prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local
    - $ {{ .Values.prometheus.host }}
  http:
    - name: http
      route:
        - destination:
            host: prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local
            port:
              number: 9090